name: Publish plugin

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # tag pattern on pub.dev: 'v{{version}'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: flutter-actions/setup-flutter@v3
      - uses: flutter-actions/setup-pubdev-credentials@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Publish
        run: flutter pub publish --force
